# Generated by Django 4.1.5 on 2023-02-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sell_count',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
