# Generated by Django 4.1.5 on 2023-02-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_alter_user_sell_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sell_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
