# Generated by Django 4.1.5 on 2023-02-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_alter_user_salary_alter_user_sell_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sell_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
