# Generated by Django 4.1.7 on 2023-02-15 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('hour', models.CharField(max_length=10)),
                ('min', models.CharField(max_length=10)),
                ('cname', models.CharField(max_length=10)),
                ('pee', models.CharField(max_length=10)),
                ('jo', models.CharField(max_length=10)),
                ('join_count', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=30)),
                ('sell', models.CharField(max_length=10)),
                ('bname', models.CharField(max_length=10)),
                ('rg', models.CharField(default='', max_length=10)),
                ('gn', models.CharField(max_length=10)),
                ('rq', models.CharField(max_length=10)),
                ('etc', models.CharField(max_length=10)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Joinlook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_name', models.CharField(max_length=10)),
                ('j_tag', models.CharField(max_length=10)),
                ('j_count', models.CharField(max_length=10)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('j_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
