# Generated by Django 4.1.5 on 2023-02-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinlook',
            name='deposit_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joinlook',
            name='deposit_status',
            field=models.BooleanField(default=False),
        ),
    ]
