# Generated by Django 4.1.5 on 2023-02-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_joinlook_deposit_request_joinlook_deposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinlook',
            name='refund_request',
            field=models.BooleanField(default=False),
        ),
    ]
