# Generated by Django 4.1.5 on 2023-02-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_joinlook_refund_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinlook',
            name='join_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
